#-----------------------------------------
# トップディレクトリを相対ディレクトリで指すようにここは修正
#-----------------------------------------
CORE_DIR=../../../src/core

#-----------------------------------------
# ここのセクションは通常変更する必要なし
#-----------------------------------------
include $(CORE_DIR)/Makefile_core_subsys_pre

#-----------------------------------------
# このディレクトリにあるソースファイルを列挙
#-----------------------------------------
CPPFILES=\
	rinaWideTextDrawDeviceNode.cpp \
	rinaWideTextPin.cpp          \
	rinaWideTextProviderNode.cpp \
	rinaMultiTextPin.cpp          \
	rinaMultiTextProviderNode.cpp \
	rinaWideTextMixerNode.cpp    \
	rinaTest.cpp

#-----------------------------------------
# ここのセクションは通常変更する必要なし
#-----------------------------------------
include $(CORE_DIR)/Makefile_core_subsys_post

