#-----------------------------------------
# トップディレクトリを相対ディレクトリで指すようにここは修正
#-----------------------------------------
CORE_DIR=../..

#-----------------------------------------
# ここのセクションは通常変更する必要なし
#-----------------------------------------
include $(CORE_DIR)/Makefile_core_subsys_pre


#-----------------------------------------
# このディレクトリにあるソースファイルを列挙
#-----------------------------------------
CPPFILES = \
		common/FSManager.cpp                     \
		osfs/OSFS.cpp                            \
		tmpfs/MemoryStream.cpp                   \
		tmpfs/TmpFS.cpp                          

#		common/FSManagerBind.cpp                 \
#		osfs/OSFSBind.cpp                        \
#		pathfs/PathFS.cpp                        \
#		pathfs/PathFSBind.cpp                    \
#		tmpfs/TmpFSBind.cpp                      \
#		xp4fs/DecompressedHolder.cpp             \
#		xp4fs/XP4Archive.cpp                     \
#		xp4fs/XP4FS.cpp                          \
#		xp4fs/XP4SegmentCache.cpp                \
#		xp4fs/XP4Stream.cpp                      \
#		xp4fs/XP4StreamCache.cpp                 \
#		xp4fs/XP4FSBind.cpp                      


#-----------------------------------------
# ここのセクションは通常変更する必要なし
#-----------------------------------------
include $(CORE_DIR)/Makefile_core_subsys_post

