#-----------------------------------------
# トップディレクトリを相対ディレクトリで指すようにここは修正
#-----------------------------------------
CORE_DIR=../..

#-----------------------------------------
# ここのセクションは通常変更する必要なし
#-----------------------------------------
include $(CORE_DIR)/Makefile_core_subsys_pre

#-----------------------------------------
# このディレクトリにあるソースファイルを列挙
#-----------------------------------------
CPPFILES=\
	rinaNode.cpp                  \
	rinaPin.cpp                   \
	rinaIdRegistry.cpp            \
	rinaQueue.cpp                 \
	test/rinaWideTextDrawDeviceNode.cpp \
	test/rinaWideTextPin.cpp          \
	test/rinaWideTextProviderNode.cpp \
	test/rinaMultiTextPin.cpp          \
	test/rinaMultiTextProviderNode.cpp \
	test/rinaWideTextMixerNode.cpp    \
	test/rinaTest.cpp

#-----------------------------------------
# ここのセクションは通常変更する必要なし
#-----------------------------------------
include $(CORE_DIR)/Makefile_core_subsys_post

