#-----------------------------------------
# トップディレクトリを相対ディレクトリで指すようにここは修正
#-----------------------------------------
CORE_DIR=../..

#-----------------------------------------
# ここのセクションは通常変更する必要なし
#-----------------------------------------
include $(CORE_DIR)/Makefile_core_subsys_pre

#-----------------------------------------
# このディレクトリにあるソースファイルを列挙
#-----------------------------------------
CPPFILES=\
	rinaNode.cpp                  \
	rinaPin.cpp                   \
	rinaIdRegistry.cpp            \
	rinaQueue.cpp                 \
	test/rinaTextDrawDeviceNode.cpp \
	test/rinaTextPin.cpp          \
	test/rinaTextProviderNode.cpp \
	test/rinaTextMixerNode.cpp    \
	test/rinaTest.cpp

#-----------------------------------------
# ここのセクションは通常変更する必要なし
#-----------------------------------------
include $(CORE_DIR)/Makefile_core_subsys_post

